import {
    Plus,
    CloseEye,
    IconArticleMenu,
    OpenEye,
    AvatarDefault,
    IconCartMenu,
    IconManageMenu,
    IconStoreMenu,
    IconLogout,
    IconLightTheme,
    IconSelectArrowLarge,
    IconInputSearch,
    IconDarkTheme,
    IconArrowRight,
    IconFilter,
    IconLineSubMenu,
    IconPrinter,
    IconSelectArrowButton,
    IconPlus,
    IconPen,
    IconWarehouse,
    IconRemove,
    IconRecycling,
    IconArrowButton, IconChecked,
} from './SVGIcon.tsx';

export default {
    IconWarehouse,
    IconPen,
    IconRecycling,
    Plus,
    CloseEye,
    IconPrinter,
    IconFilter,
    IconRemove,
    IconLineSubMenu,
    IconInputSearch,
    OpenEye,
    AvatarDefault,
    IconManageMenu,
    IconSelectArrowButton,
    IconArrowButton,
    IconCartMenu,
    IconArticleMenu,
    IconLightTheme,
    IconPlus,
    IconArrowRight,
    IconSelectArrowLarge,
    IconDarkTheme,
    IconLogout,
    IconStoreMenu,
    IconChecked,
}
