export const STORAGE_ITEM ={
    TOKEN: 'token',
    REFRESH_TOKEN: 'refresh_token',
    ROLE_ID: 'role_id',
    USER_ID: 'user_id',
    ENV_KEY: 'env_key',
    STORE_ID: 'store_id',
    STORE_PARENT_ID: 'store_parent_id',
    USER_INFO: 'user_info',
    API_URL:'api_url',
    PERMISSIONS: 'permissions',
    ROLE_OBJECT: 'role_object',
    ENV_CODE: 'env_type_code',
    IS_AUTHENTICATED: 'isAuthenticated',
    FULL_NAME: 'full_name',
    NAME_ROLE: 'name_role',
    PRINTER_VALUE: 'printer_value',
    STORE_LEVEL: 'store_level',
    PERMISSION_USER: 'permission_user',
    VIEW_IMAGE_URL: 'view_image_url',
}
